#!/usr/bin/env bash
# Transfer a file from our client to a server

if [ $# -lt 4 ];then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi

file_path=$1
server_ip=$2
username=$3
ssh_key=$4


scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path"\
	"$username"@"$server_ip":~/
