#!/usr/bin/env bash
# script that configures a new ubuntu machine to respect above requirements

sudo pat-get update -y
sudo apt-get install nginx -y

# code to redirect a specific endpoint (eg: redirect /redircet_me to hhtps://churchycodes.co.tz
echo "Hello World!" | sudo tee /var/www/html/index.html
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/churchycodes.co.tz permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-available/default

# code to create error page and add a redirect for 404
echo "Ceci n'est pas une page\n" | sudo tee /var/www/html/404.html
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-available/default

# restart the server 
sudo service nginx restart
