#!/usr/bin/env bash
# This is the script that displays number from 1 to 100
# Display FizzBuzz when the number is a multiple of 3 and 5
# Diplay Fizz when numbbetr is multiple of 3
# Displaty Buzz when number is multiple of 5
# otherwise display number
i=1
while [ $i -le 100 ]
do
	if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ];then
	   echo "FizzBuzz"
	elif [ $((i % 5)) -eq 0 ];then
		echo "Buzz"
	elif [ $((i % 3)) -eq 0 ];then
		echo "Fizz"
	else
		echo "$i"
	fi
	(( i++ ))
done
