#!/usr/bin/env bash
# The script that displays the content of the file /etc/passwd
# should display
# username
# userid
# homedirectory
file="/etc/passwd"
while read -r line
do
	echo "$line" | cut -d ":" -f1,3,6
done < "$file"
