#!/usr/bin/env bash
# This script displays numbers from 1 to 20th and display
# 4 and then bad luck from china forr the fort loop iteration
# 9 nad the bad luck from japan for the 9th iteration
# displays 17 and then bad luck from italy for the 17th iterations
i=1
while [ $i -le 20 ]
do
	echo "$i"
	case "$i" in
		 4)
		 echo "bad luck from China"
		 ;;
		 9)
		 echo "bad luck from Japan"
		 ;;
		 17)
		 echo "bad luck from Italy"
		 ;;
	esac
	(( i++ ))
done