#!/usr/bin/env bash
# Script that displays the time for 12 hours and 59  minutes
# display hours from 0 to 12
# display minutes from 1 to 59
HOUR=0
while [ $HOUR -le 12 ]
do
	MINUTE=1
	echo "Hour: $HOUR"
	while [ $MINUTE -le 59 ]
	do
		echo "$MINUTE"
		(( MINUTE++ ))
	done
	(( HOUR++ ))
done
