#!/usr/bin/env bash
# This script gives you informationabout the school file
# the script check if the file exists and print:
# if exist: school file exits
# if the file doesnot exit: school file does notexist
# if the file exists, print:
# if is empty: school file is epmty
# if is not empty: school file is not epmty
# if is a regular file : school file is regular
# if the file is not the regular file
# if the file is not regual file(nothing)
file="school"
if [ -e "$file" ];then
   echo "school file exist"
   if [ -s "$file" ];then
		echo "school file is not empty"
   else
		echo "school file is empty"
   fi
   if [ -f "$file" ];then
		echo "school is the regular file"
   fi

else
	echo "school file does not exist"
fi
