#!/usr/bin/env bash
# Fxes a web server to run nginx as nginx user listening on port 8080

# set a  user in the config by replace 'user' and its value
sed -i "s/user www-data/user nginx/" /etc/nginx/nginx.conf

# replace port 80 with 8080 in the sites-available default file
sed -i "s/80/800/g" /etc/nginx/sites-available/default
# give owner permissions to read and write to the config file
chmod 644 /etc/nginx/nginx.conf
# apache may interfere with nginx so kill the process if it is running
pkill apache2
# now start the nginx service with the new nginx user
sudo -u nginx service nginx start